site_name: Sample
title: Sample
site_description: Sample project
site_author: MP Swamy
date: Jan 01,2023
theme:
  name: "material"
nav:
  - Home: index.md
  - Docs: yagna.md
plugins:
- mkdocstrings:
    enabled: !ENV [ ENABLE_MKDOCSTRINGS, true ]
    default_handler: python
    handlers:
      python:
        options:
          show_submodules: true
          selection_opt: true
          rendering_opt: "value"