name: mkdocs
on: [push, pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - id: check
        uses: actions/version-check@v2
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocstrings-python
      - run: pip install mkdocs-material
      - run: mkdocs build
      - run: mkdocs gh-deploy --force
