name: mkdocs
on: [push, pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: pip install mkdocstrings-python
      - run: pip install mkdocs-material
      - run: mkdocs build
      - run: mkdocs gh-deploy --force
